rentahouse/core/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^listar$', listar, name='imovel_listar'),
    url(r'^novo$', adicionar, name='imovel_adicionar'),
    url(r'^alterar/(?P<pk>[0-9]+)$', alterar, name='imovel_alterar'),
    url(r'^excluir/(?P<pk>[0-9]+)$', excluir, name='imovel_excluir'),
]

rentahouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
import rentahouse.core.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', rentahouse.core.views.listar),
    re_path(r'^imovel/', include('rentahouse.core.urls')),
    re_path(r'^', include('rentahouse.usuario.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rentahouse/usuario/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^entrar$', entrar, name='usuario_entrar'),
    url(r'^sair$', sair, name='usuario_sair'),
]

rentahouse/core/models.py
from django.db import models
from .validators import valida_cep, valida_telefone


class Imovel(models.Model):

    TIPO_CHOICES = (
        ('AP', 'Apartamento'),
        ('CS', 'Casa'),
        ('CF', 'Condomínio fechado'),
        ('SB', 'Sobrado')
    )
    QUARTO_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5 ou mais')
    )

    UF_CHOICES = (
        ('AC', 'AC'),
        ('AL', 'AL'),
        ('AP', 'AP'),
        ('AM', 'AM'),
        ('BA', 'BA'),
        ('CE', 'CE'),
        ('DF', 'DF'),
        ('ES', 'ES'),
        ('GO', 'GO'),
        ('MA', 'MA'),
        ('MT', 'MT'),
        ('MS', 'MS'),
        ('MG', 'MG'),
        ('PA', 'PA'),
        ('PB', 'PB'),
        ('PR', 'PR'),
        ('PE', 'PE'),
        ('PI', 'PI'),
        ('RJ', 'RJ'),
        ('RN', 'RN'),
        ('RS', 'RS'),
        ('RO', 'RO'),
        ('RR', 'RR'),
        ('SC', 'SC'),
        ('SP', 'SP'),
        ('SE', 'SE'),
        ('TO', 'TO'),
    )
    
    titulo = models.CharField(max_length=100, null=False, blank=False)
    descricao = models.TextField(null=False, blank=False)
    tipo = models.CharField(max_length=20, choices=TIPO_CHOICES, null=False, blank=False)
    qt_quartos = models.PositiveIntegerField(choices=QUARTO_CHOICES, blank=False)
    area = models.PositiveIntegerField(null=True, blank=True)
    qt_vagas_garagem = models.PositiveIntegerField(null=False, blank=False)
    vl_aluguel = models.DecimalField(max_digits=12, decimal_places=2, null=False, blank=False)
    cep = models.CharField(max_length=9, null=False, blank=False, validators=[valida_cep])
    logradouro = models.CharField(max_length=80, null=True, blank=True)
    bairro = models.CharField(max_length=50, null=True, blank=True)
    municipio = models.CharField(max_length=50, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True, choices=UF_CHOICES)
    telefone = models.CharField(max_length=15, null=False, blank=True, validators=[valida_telefone])
    dh_insercao = models.DateTimeField(auto_now_add=True)
    dh_alteracao = models.DateTimeField(auto_now=True)
    foto = models.FileField(null=True, blank=True, upload_to='anuncios/%Y/%m/%d/')

rentahouse/usuario/models.py
from django.db import models

# Create your models here.

rentahouse/core/forms.py
from django.forms import ModelForm, widgets
from .cleaners import manter_digitos
from .models import Imovel


class ImovelFormClean(ModelForm):
    def clean_telefone(self):
        telefone = self.cleaned_data['telefone']
        return manter_digitos(telefone)

    def clean_cep(self):
        cep = self.cleaned_data['cep']
        return manter_digitos(cep)

    def clean(self):
        self.cleaned_data = super().clean()
        return self.cleaned_data


class ImovelForm(ImovelFormClean):
    class Meta:
        model = Imovel
        fields = [
            'titulo',
            'descricao',
            'tipo',
            'qt_quartos',
            'area',
            'qt_vagas_garagem',
            'vl_aluguel',
            'cep',
            'logradouro',
            'bairro',
            'municipio',
            'uf',
            'telefone',
            'foto',
        ]
        labels = {
            'titulo': 'Título*',
            'descricao': 'Descrição*',
            'tipo': 'Tipo imóvel*',
            'qt_quartos': 'Quartos*',
            'area': 'Área (m²)',
            'qt_vagas_garagem': 'Vagas na garagem*',
            'vl_aluguel': 'Aluguel (R$)*',
            'cep': 'CEP*',
            'logradouro': 'Logradouro',
            'bairro': 'Bairro',
            'municipio': 'Município',
            'uf': 'UF',
            'telefone': 'Telefone*',
            'foto': 'Imagem',
        }
        widgets = {
            'descricao': widgets.Textarea(attrs={'class': 'materialize-textarea'}),
        }

rentahouse/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import ImovelForm, Imovel
from django.db.models import Q


def paginador(request, qt_por_pagina, lista):
    resultados_por_pagina = request.GET.get("resultados_por_pagina")

    if not resultados_por_pagina or not resultados_por_pagina.isdigit():
        resultados_por_pagina = qt_por_pagina

    paginador = Paginator(lista, resultados_por_pagina)

    pagina = request.GET.get('pagina')

    try:
        pagina_atual = paginador.page(pagina)
    except PageNotAnInteger:
        pagina = 1
        pagina_atual = paginador.page(pagina)
    except EmptyPage:
        pagina = paginador.num_pages
        pagina_atual = paginador.page(pagina)

    lista_paginas = []
    for i in range(paginador.num_pages):
        lista_paginas.append(i + 1)

    paginacao = [
        pagina_atual,
        pagina,
        lista_paginas
    ]
    return paginacao


def listar(request, template_name='imovel_listar.html'):
    pesquisa = request.GET.get("pesquisa")
    if pesquisa:
        imoveis = Imovel.objects.filter(
            Q(logradouro__icontains=pesquisa) |
            Q(bairro__icontains=pesquisa) |
            Q(municipio__icontains=pesquisa) |
            Q(uf__icontains=pesquisa) |
            Q(cep__icontains=pesquisa)
        )
    else:
        pesquisa = ''
        imoveis = Imovel.objects.all().order_by('-id')

    paginacao = paginador(request, 10, imoveis)

    template_data = {
        'lista': imoveis,
        'pesquisa': pesquisa,
        'pagina_atual': paginacao[0],
        'pagina': paginacao[1],
        'lista_paginas': paginacao[2],
    }

    return render(request, template_name, template_data)


@login_required
def adicionar(request, template_name='imovel_form.html'):
    imovel = ImovelForm(request.POST, request.FILES)
    if imovel.is_valid():
        imovel.save()
        return redirect('imovel_listar')
    else:
        imovel = ImovelForm()
    return render(request, template_name, {'titulo': 'Novo', 'form': imovel})


@login_required
def excluir(request, pk, template_name='imovel_excluir.html'):
    imovel = Imovel.objects.get(pk=pk)
    if request.method == 'POST':
        imovel.delete()
        return redirect('imovel_listar')

    return render(request, template_name, {'titulo': 'Excluir', 'imovel': imovel})


@login_required
def alterar(request, pk, template_name='imovel_form.html'):
    imovel = get_object_or_404(Imovel, pk=pk)
    if request.method == "POST":
        imovelForm = ImovelForm(request.POST, request.FILES, instance=imovel)
        if imovelForm.is_valid():
            imovelForm.save()
            return redirect('imovel_listar')
    else:
        imovelForm = ImovelForm(instance=imovel)
    return render(request, template_name, {'titulo': 'Alterar', 'form': imovelForm})

rentahouse/usuario/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect


def entrar(request, template_name='entrar.html'):
    next = request.GET.get('next', '/')
    if request.method == "POST":
        nome_usuario = request.POST['nome_usuario']
        senha = request.POST['senha']
        usuario = authenticate(username=nome_usuario, password=senha)
        if usuario is not None:
            login(request, usuario)
            return redirect(next)
        else:
            messages.error(request, 'Usuário ou senha incorreto.')
            return redirect(settings.LOGIN_URL)

    return render(request, template_name, {'redirect_to': next})


def sair(request):
    logout(request)
    return HttpResponseRedirect('/')

rentahouse/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt_BR">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css" rel="stylesheet" media="screen,projection"/>

        <title>Rent a House{% block title %}{% endblock title %}</title>
    </head>
    <body class="white">
        <main>
            <ul id="ddwUsuario" class="dropdown-content">
                <li>
                    <a href="{% url 'usuario_sair' %}" class="orange-text">
                        <i class="left small material-icons">exit_to_app</i>Sair
                    </a>
                </li>
            </ul>

            <!--NAVBAR INICIO-->
            <ul id="menu-mobile" class="side-nav">
                <!--DDW USUARIO-->
                <ul class="collapsible collapsible-accordion">
                    {% if not request.user.is_authenticated %}
                    <li>
                        <a class="collapsible-header orange-text" href="{% url 'usuario_entrar' %}">
                            <i class="left material-icons orange-text">person</i>Login
                        </a>
                    </li>

                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li>
                        <a class="collapsible-header orange-text" href="{% url 'imovel_listar' %}">
                            <i class="left material-icons orange-text">settings</i>Gerenciar
                        </a>
                    </li>
                    <li>
                        <a class="collapsible-header orange-text">
                            <i class="material-icons left orange-text">person</i>
                            {#                                {{ request.user.first_name }}#} Luis
                            <i class="material-icons right orange-text">arrow_drop_down</i>
                        </a>
                        <div class="collapsible-body">
                            <ul>
                                <li>
                                    <a class="orange-text" href="{% url 'usuario_sair' %}">
                                        <i class="left small material-icons orange-text">exit_to_app</i>
                                        Sair
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </ul>
            <!--NAVBAR FIM-->

            <!--MENU MOBILE INICIO-->
            <div class="navbar-fixed">
                <nav>
                    <div class="nav-wrapper light-blue lighten-1">
                        <!--LOGO-->
                        <a href="/" class="brand-logo left">Rent a House</a>

                        <!--ICONE MENU MOBILE-->
                        <a href="#" data-activates="menu-mobile" class="button-collapse right">
                            <i class="material-icons">menu</i>
                        </a>

                        <!--MENU DEFAULT INICIO-->
                        {% if request.user.is_authenticated %}
                        <!--DDW USUARIO-->
                        <ul class="right hide-on-med-and-down">
                            <li>
                                <a class="dropdown-button" href="" data-activates="ddwUsuario">
                                    <i class="material-icons left">person</i>
                                    {{ request.user }}
                                    <i class="material-icons right">arrow_drop_down</i>
                                </a>
                            </li>
                        </ul>
                        <ul class="right hide-on-med-and-down">
                            <li>
                                <a href="{% url 'imovel_listar' %}">
                                    <i class="left material-icons">settings</i>Gerenciar
                                </a>
                            </li>
                        </ul>
                        {% endif %}
                        {% if not request.user.is_authenticated %}
                        <ul class="right hide-on-med-and-down">
                            <li>
                                <a href="{% url 'usuario_entrar' %}">
                                    <i class="left material-icons">person</i>Login
                                </a>
                            </li>
                        </ul>
                        {% endif %}

                        <!--MENU DEFAULT FIM-->
                    </div>
                </nav>
            </div>
            <!--MENU MOBILE FIM-->
            {% block content %}

            {% endblock %}
        </main>

        <!--  Scripts-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
        <script>
        $( document ).ready(function() {
            $(".button-collapse").sideNav({
                edge: 'right',
                draggable: true
                }
            );
            $('.dropdown-button').dropdown({
                constrainWidth: false,
                belowOrigin: true
                }
            );
        });
        </script>
        {% block script %}
        {% endblock %}
    </body>
</html>

rentahouse/core/templates/imovel_excluir.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
- Imóvel - {{ titulo }}
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col s12 m6 offset-m3 l6 offset-l3">
        <div class="section">
            <h4 class="medium">Imóvel <small>{{ titulo }}</small></h4>
        </div>
        <div class="divider"></div>
    </div>
</div>

<div class="row">
    <form method="post" class="col s12 m6 offset-m3 l6 offset-l3 flow-text">
    {% csrf_token %}
        <div class="row">
            <div class="col s12 flow-text">
                <p>Tem certeza que deseja excluir o seguinte anúncio ?</p>
                <p><b>Título:</b> {{ imovel.titulo }}</p>
                <p><b>Aluguel:</b> {{ imovel.vl_aluguel }}</p>
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m12">
                <button type="submit" class="waves-effect waves-light btn btn-primary orange">
                    <i class="material-icons left">check</i>Remover
                </button>
                <a href="{% url 'imovel_listar' %}" class="waves-effect waves-light grey darken-2 btn btn-primary">
                    <i class="material-icons left">cancel</i>Cancelar
                </a>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

rentahouse/core/templates/imovel_form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
- Imóvel - {{ titulo }}
{% endblock title %}

{% block content %}
<div class="container">
        <div class="row">
            <div class="col s12 m10 offset-m1 l10 offset-l1">
                <div class="section">
                    <h4 class="medium">Imóvel <small>{{ titulo }}</small></h4>
                </div>
                <div class="divider"></div>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m10 offset-m1 l10 offset-l1 margin-20">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% load filters %}
                    <div class="row">
                        <div class="input-field col s12">
                            {% if form.titulo.errors %}
                                {{ form.titulo|add_validate_invalid_class_in_input }}
                                {{ form.titulo|add_error_msg_in_label }}
                             {% else %}
                                {{ form.titulo }}
                                {{ form.titulo.label_tag }}
                             {% endif %}
                        </div>
                        <div class="input-field col s12">
                            {% if form.descricao.errors %}
                                {{ form.descricao|add_validate_invalid_class_in_input }}
                                {{ form.descricao|add_error_msg_in_label }}
                             {% else %}
                                {{ form.descricao }}
                                {{ form.descricao.label_tag }}
                             {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <label>Imagem:</label><br>
                            {{ form.foto }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m4">
                             {% if form.tipo.errors %}
                                {{ form.tipo|add_validate_invalid_class_in_input }}
                                {{ form.tipo|add_error_msg_in_label }}
                             {% else %}
                                {{ form.tipo }}
                                {{ form.tipo.label_tag }}
                             {% endif %}
                        </div>
                        <div class="input-field col s12 m2">
                            {% if form.qt_quartos.errors %}
                                {{ form.qt_quartos|add_validate_invalid_class_in_input }}
                                {{ form.qt_quartos|add_error_msg_in_label }}
                            {% else %}
                                {{ form.qt_quartos }}
                                {{ form.qt_quartos.label_tag }}
                            {% endif %}
                        </div>
                        <div class="input-field col s12 m3">
                            {% if form.area.errors %}
                                {{ form.area|add_validate_invalid_class_in_input }}
                                {{ form.area|add_error_msg_in_label }}
                            {% else %}
                                {{ form.area }}
                                {{ form.area.label_tag }}
                            {% endif %}
                        </div>
                        <div class="input-field col s12 m3">
                            {% if form.qt_vagas_garagem.errors %}
                                {{ form.qt_vagas_garagem|add_validate_invalid_class_in_input }}
                                {{ form.qt_vagas_garagem|add_error_msg_in_label }}
                            {% else %}
                                {{ form.qt_vagas_garagem }}
                                {{ form.qt_vagas_garagem.label_tag }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m4">
                            {% if form.vl_aluguel.errors %}
                                {{ form.vl_aluguel|add_validate_invalid_class_in_input }}
                                {{ form.vl_aluguel|add_error_msg_in_label }}
                            {% else %}
                                {{ form.vl_aluguel }}
                                {{ form.vl_aluguel.label_tag }}
                            {% endif %}
                        </div>
                        <div class="input-field col s12 m4">
                            {% if form.telefone.errors %}
                                {{ form.telefone|add_validate_invalid_class_in_input }}
                                {{ form.telefone|add_error_msg_in_label }}
                            {% else %}
                                {{ form.telefone }}
                                {{ form.telefone.label_tag }}
                            {% endif %}
                        </div>
                        <div class="input-field col s12 m4">
                            {% if form.cep.errors %}
                                {{ form.cep|add_validate_invalid_class_in_input }}
                                {{ form.cep|add_error_msg_in_label }}
                            {% else %}
                                {{ form.cep }}
                                {{ form.cep.label_tag }}
                            {% endif %}
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12 m4">
                            {% if form.logradouro.errors %}
                                {{ form.logradouro|add_validate_invalid_class_in_input }}
                                {{ form.logradouro|add_error_msg_in_label }}
                            {% else %}
                                {{ form.logradouro }}
                                {{ form.logradouro.label_tag }}
                            {% endif %}
                        </div>
                        <div class="input-field col s12 m3">
                            {% if form.bairro.errors %}
                                {{ form.bairro|add_validate_invalid_class_in_input }}
                                {{ form.bairro|add_error_msg_in_label }}
                            {% else %}
                                {{ form.bairro }}
                                {{ form.bairro.label_tag }}
                            {% endif %}
                        </div>
                        <div class="input-field col s12 m3">
                            {% if form.municipio.errors %}
                                {{ form.municipio|add_validate_invalid_class_in_input }}
                                {{ form.municipio|add_error_msg_in_label }}
                            {% else %}
                                {{ form.municipio }}
                                {{ form.municipio.label_tag }}
                            {% endif %}
                        </div>
                        <div class="input-field col s12 m2">
                            {% if form.uf.errors %}
                                {{ form.uf|add_validate_invalid_class_in_input }}
                                {{ form.uf|add_error_msg_in_label }}
                            {% else %}
                                {{ form.uf }}
                                {{ form.uf.label_tag }}
                            {% endif %}
                        </div>
                    </div>

                    {% if form.errors %}
                    <div class="row">
                        <div class="col s12">
                        {% for error in form.non_field_errors %}
                        <div style="color: red;">
                            {{ error|escape }}
                        </div>
                        {% endfor %}
                        </div>
                    </div>
                    {% endif %}

                    <div class="col s12">
                        <button id='btn_salvar' type="submit"
                                class="waves-effect waves-light btn btn-primary orange">
                        <i class="material-icons left">save</i>Enviar anúncio
                        </button>
                        <a href="{% url 'imovel_listar' %}"
                           class="waves-effect waves-light grey darken-2 btn btn-primary">
                            <i class="material-icons left">cancel</i>
                            Voltar
                        </a>
                    </div>
                </form>
            </div>
        </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $( document ).ready(function() {
        $('select').material_select();
    });
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js"></script>
<script src="{% static 'core/js/formata_campo.js' %}"></script>
<script src="{% static 'core/js/busca_endereco.js' %}"></script>
{% endblock script %}

rentahouse/core/templates/imovel_listar.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
- Imóveis
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col s12 m10 offset-m1 l10 offset-l1">
        <div class="section">
            <h4 class="medium">Imóveis</h4>
        </div>
        <div class="divider"></div>
    </div>
</div>

<div class="row">
    <div class="col s12 m10 offset-m1 l10 offset-l1">
        <nav>
            <div class="nav-wrapper white">
                <form method="get">
                    <div class="input-field">
                        <input id="pesquisa" name="pesquisa" type="search" value="{{ pesquisa }}"
                               placeholder="Busca por endereço">
                        <label class="label-icon valign-wrapper" for="pesquisa">
                            <i class="material-icons grey-text lighten-3">search</i>
                        </label>
                        <i class="material-icons">close</i>
                    </div>
                </form>
            </div>
        </nav>
    </div>
</div>
{% if request.user.is_authenticated %}
<div class="row">
    <div class="col s12 m10 offset-m1 l10 offset-l1">
        <a href="{% url 'imovel_adicionar' %}" class="waves-effect waves-light btn btn-primary orange">
            <i class="material-icons left">add</i>
            Novo
        </a>
    </div>
</div>
{% endif %}

<div class="row">
    <div class="col s12 m10 offset-m1 l10 offset-l1">
        <div class="row">
            {% for imovel in pagina_atual %}
                <div class="col s12">
                    <div class="card z-depth-3">
                        <div class="card-image">
                            <img src="{{ imovel.foto.url }}">
                        </div>
                        <div class="card-content">
                            <span class="card-title"><b>{{ imovel.titulo }}</b></span>
                            <p><b>Tipo: </b>{{ imovel.get_tipo_display }}</p>
                            <p><b>Área: </b>{{ imovel.area }} m²</p>
                            <p><b>Quartos: </b>{{ imovel.qt_quartos }}</p>
                            <p><b>Vaga garagem: </b>{{ imovel.qt_vagas_garagem}}</p>
                            <p><b>Aluguel: </b>R$ {{ imovel.vl_aluguel }}</p>
                            <p><b>Telefone: </b>
                                <span {% if imovel.telefone|length == 11 %}
                                            class="tel11"
                                        {% elif imovel.telefone|length == 10 %}
                                            class="tel10"
                                        {% endif %}>
                                {{ imovel.telefone }}
                                </span>
                            </p>
                            <p><b>Endereço: </b>{{ imovel.logradouro }} - {{ imovel.bairro }} - {{ imovel.municipio }} - {{ imovel.uf }}</p>
                            <p><b>CEP: </b><span class="cep">{{ imovel.cep }}</span> </p>
                            <span><b><u>Descrição</u></b></span>
                            <p>{{ imovel.descricao }}</p>
                        </div>
                        {% if request.user.is_authenticated %}
                        <div class="card-action">
                            <a href="{% url 'imovel_alterar' imovel.pk %}" class="btn orange">
                                <i class="left material-icons">edit</i>Editar
                            </a>
                            <a href="{% url 'imovel_excluir' imovel.pk %}" class="btn orange">
                                <i class="left material-icons">delete</i>Excluir
                            </a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>


{% include 'paginador.html' %}

{% endblock content %}

{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.13/jquery.mask.min.js"></script>
<script src="{% static 'core/js/formata_texto.js' %}"></script>
{% endblock script %}

rentahouse/core/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h1>NO AR</h1>

{% endblock content %}

rentahouse/usuario/templates/entrar.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
- Entrar
{% endblock title %}

{% block content %}
<div class="section"></div>
<main style="text-align: center">
    <h5>Informe seu acesso</h5>
        <div class="row">
            <form class="col s12 m6 offset-m3 l4 offset-l4" method="post" action="{% url 'usuario_entrar' %}?next={{ redirect_to }}" novalidate="novalidate">
                {% csrf_token %}
                <div class='row'>
                    <div class='col s12'>
                    </div>
                </div>

                <div class='row'>
                    <div class='input-field col s12'>
                        <input type="text" name="nome_usuario" id="nome_usuario">
                        <label for='nome_usuario'>Digite seu usuário</label>
                    </div>
                </div>

                <div class='row'>
                    <div class='input-field col s12'>
                        <input type="password" name="senha" id="senha">
                        <label for='senha'>Digite sua senha</label>
                    </div>
                </div>

                <div class='row'>
                    <button type='submit' name='btn_login' class="btn btn-large waves-effect orange col s12">
                        <i class="small material-icons col s2 offset-s3">send</i>
                        <span class="col s2">Entrar</span>
                    </button>
                </div>
            </form>
        </div>

</main>
<div class="section"></div>
{% endblock content %}

{% block script %}
{% if messages %}
<script>
    $(document).ready(function(){
    {% for message in messages %}
        Materialize.toast('{{ message }}' ,4000);
    {% endfor %}
    });
</script>
{% endif %}
{% endblock script %}